### PR TITLE
Fix example post file format(yyyy-mm-dd HHmmss-post-tile.md)

### PR DESCRIPTION
**Pull request by koba04**
Posted file format is defined as "yyyy-mm-dd HHmmss-post-tile.md" in README.md.

### CODE REVIEW

**Comment by vesparny** [comment]
The pattern you modified is used all over the application for fetching files.
If we want to change it we should do it in every file.

Why do you propose to change it?

**Comment by koba04** [comment]
Sorry, I saw it wrong...

But I prefer to avoid included  a space in file name because that is often cumbersome.

proposal:
1. `yyyy-mm-dd-HHmmss-post-title.md`
2. `yyyy-mm-dd-post-title.md` (cf. [Octopress](http://octopress.org/docs/blogging/))

What do you think about it?

If there aren't any problems, I'd like to pull request again.

**Comment by vesparny** [comment]
Ok, 
We should go for your proposal 1.
The second one could not be used because I use the 'HHmmss' for sorting post issued in the same day.

**Comment by koba04** [comment]
Thank you!
I close this issue once and will send a pull request.

**Comment by vesparny** [comment]
Ok, but you can also use the same one, just squash the commit when you are done.

**Comment by koba04** [comment]
Ok, I will do so from next time.

**Pull request closed without merging**
